### PR TITLE
dotenv

### PR DESCRIPTION
**Pull request by juhangsin**

### CODE REVIEW

**Comment by juhangsin** [comment]
is it okay to have password for mysql to be @ dotenv file?
```
MYSQL_PASSWORD=password
MYSQL_USER=a12nserver
MYSQL_DATABASE=a12nserver
```

**Comment by mhum** [comment]
I think it's okay since these are the defaults and it is set up in such a way that a real deployment can provide their own credentials. The "better" way would be to continue using environmental variables (which this doesn't prevent people from doing).

It would probably be nice to have a big, fat, scary warning in the logs on startup if the default values are still being used.

**Comment by juhangsin** [comment]
@mhum & @evert, is it okay to merge this in?

**Comment by mhum** [comment]
shipit!

**Pull request merged**
