### PR TITLE
Tslint to eslint

### PR DESCRIPTION
**Pull request by juhangsin**

### CODE REVIEW

**Comment by juhangsin** [comment]
Currently this won't pass Travis CI test

**Comment by mhum** [comment]
++ Now I don't need to make sure my spacing matches everything else

**Comment by juhangsin** [comment]
> ++ Now I don't need to make sure my spacing matches everything else

@mhum hahaha go 8 spaces if you wanted to, and eslint will say 'no' and fix it for you later.

**Comment by evert** [comment]
@juhangsin humisiston is now using this branch, could you try and get this merged?

**Pull request merged**
